services:
  db:
    image: postgres:17-alpine3.21
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: servim_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: