// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Appointment struct {
	ID          string    `json:"id"`
	Description string    `json:"description"`
	Datetime    time.Time `json:"datetime"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Branch struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	Address     string        `json:"address"`
	Specialists []*Specialist `json:"specialists"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type Company struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Branches  []*Branch `json:"branches"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Mutation struct {
}

type NewCompany struct {
	Title string `json:"title"`
}

type Query struct {
}

type Service struct {
	ID           string         `json:"id"`
	Price        float64        `json:"price"`
	Appointments []*Appointment `json:"appointments"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type Specialist struct {
	ID        string     `json:"id"`
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	Weekends  []*int32   `json:"weekends"`
	WorkFrom  time.Time  `json:"work_from"`
	WorkUntil time.Time  `json:"work_until"`
	Services  []*Service `json:"services,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type User struct {
	ID           string         `json:"id"`
	FirstName    string         `json:"firstName"`
	LastName     string         `json:"lastName"`
	Appointments []*Appointment `json:"appointments"`
	Phone        string         `json:"phone"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}
